listeningPort: 4000
listeningHost: 172.17.0.2

fileTracker: "wss://tracker.openwebtorrent.com"

tls:
  cert: ./certs/cert.pem
  key: ./certs/privkey.pem

turnAPIURI: "https://host.domain.tld/turn"
turnAPIKey: "Your API key"

backupTurnServers:
  - urls:
      - "turn:numb.viagenie.ca"
    username: "webrtc@live.com"
    credential: "muazkh"

redisOptions:
  host: "172.17.0.4"
  port: "6379"
  password: "12345678"

prometheus:
  enabled: false
  deidentify: true
  numeric: true
  listen: host.domain.tld

mediasoup:
  webRtcTransport:
    listenIps:
      - ip: "172.17.0.2"
        announcedIp: null